# Generated by Django 5.2.4 on 2025-08-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_event_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descripcion',
            new_name='descripción',
        ),
        migrations.AddField(
            model_name='event',
            name='ubicación',
            field=models.TextField(default='Ubicación pendiente'),
            preserve_default=False,
        ),
    ]
