# Generated by Django 5.2.4 on 2025-08-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_descripcion_event_descripción_event_ubicación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ubicación',
            field=models.CharField(max_length=255),
        ),
    ]
