# Generated by Django 5.2.4 on 2025-08-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_ubicación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descripción',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
